name: Check GCP action
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: "auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v2.1.3"
        with:
          create_credentials_file: "true"
          workload_identity_provider: "projects/gcp-labs-bshmo8bb/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider" # In the providerId, the numerical project ID (12 digit number) should be used
          service_account: "iam-lab-7-target@gcp-labs-bshmo8bb.iam.gserviceaccount.com" # instead of the alphanumeric project ID. ex:
      - id: "gcloud"
        name: "gcloud"
        run: |-
          gcloud auth list
          gcloud projects list
          gcloud secrets list
